[package]
name = "jsonrpc-derive"
version = "9.0.0"
authors = ["Andrew Jones <ascjones@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
serde = "1.0"
jsonrpc-core = { version = "9.0", path = "../core" }
jsonrpc-pubsub = { version = "9.0", path = "../pubsub" }
syn = { version = "0.15", features = ["full", "extra-traits"] }
proc-macro2 = "0.4"
quote = "0.6"
